import type { Attendance, Employee, Viewer, WorkspaceData } from "./types";

// Fictional data only. This module is never used to authenticate real accounts.
export const demoId = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const departmentId = (n: number) => demoId(100 + n);
const hrPermissions = [
  "employees.read",
  "employees.manage",
  "private.read",
  "private.write",
  "workforce.summary",
  "attendance.read",
  "attendance.manage",
  "schedules.manage",
  "leave.read",
  "leave.approve",
  "documents.read",
  "documents.manage",
  "performance.read",
  "performance.manage",
  "tasks.manage",
  "announcements.manage",
  "organization.manage",
  "audit.read",
  "recruitment.manage",
];
export const demoViewer: Viewer = {
  id: demoId(509),
  employee_id: demoId(9),
  name: "Maya Chen",
  email: "maya.chen@example.test",
  job_title: "People Operations Manager",
  profile_type: "Managerial",
  roles: ["Managerial", "HR Administrator", "Recruitment Officer"],
  grants: hrPermissions.map((permission) => ({ permission, scope: "company" })),
  mfa_required: true,
  status: "active",
  session_valid: true,
  aal: "aal2",
};
export function makeDemoData(now = new Date()): WorkspaceData {
  const day = (offset: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + offset);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  };
  const stamp = (offset: number, time = "09:00") => `${day(offset)}T${time}:00+08:00`;
  const year = now.getFullYear();
  const period = (offset: number) => {
    const d = new Date(now.getFullYear(), now.getMonth() + offset, 1);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
  };
  const departments = [
    { id: departmentId(1), name: "People & Culture", color: "#178579", parent_id: null },
    { id: departmentId(2), name: "Engineering", color: "#6a85d5", parent_id: null },
    { id: departmentId(3), name: "Marketing", color: "#c39b60", parent_id: null },
    { id: departmentId(4), name: "Finance", color: "#9b82bd", parent_id: null },
    { id: departmentId(5), name: "Operations", color: "#81aaa2", parent_id: null },
    { id: departmentId(6), name: "Leadership", color: "#b5becc", parent_id: null },
    { id: departmentId(7), name: "Sales", color: "#dba6a0", parent_id: null },
  ];
  const teams = departments.map((d, index) => ({
    id: demoId(201 + index),
    name: d.name === "Engineering" ? "Product & technology" : `${d.name} team`,
    department_id: d.id,
  }));
  const rows: [string, string, string, number, number | null][] = [
    ["Sofia Reyes", "Owner", "Company Owner", 6, null],
    ["Daniel Foster", "President", "President", 6, 1],
    ["Amara Okafor", "Vice-President", "VP, Business Operations", 5, 4],
    ["Henry Patel", "CEO", "Chief Executive Officer", 6, 2],
    ["Ethan Cruz", "COO", "Chief Operating Officer", 5, 4],
    ["Isabella Santos", "CFO", "Chief Financial Officer", 4, 4],
    ["Lucas Tan", "CMO", "Chief Marketing Officer", 3, 4],
    ["Zoe Williams", "Director", "Engineering Director", 2, 4],
    ["Maya Chen", "Managerial", "People Operations Manager", 1, 2],
    ["Noah Kim", "Supervisor", "Operations Supervisor", 5, 5],
    ["Priya Shah", "Specialist", "Senior Product Designer", 2, 8],
    ["Marcus Reed", "Rank & File", "Sales Associate", 7, 3],
    ["Elena Garcia", "Janitorial", "Facilities Associate", 5, 10],
    ["Oliver Santos", "Skilled & Labor", "Maintenance Technician", 5, 10],
    ["Chloe Martin", "Intern / Trainee", "Software Engineering Intern", 2, 8],
    ["Sam Rivera", "Others", "Workplace Coordinator", 1, 9],
    ["Lena Brooks", "Specialist", "HR Officer", 1, 9],
    ["Ryan Cole", "Specialist", "Payroll Specialist", 4, 6],
    ["Aisha Johnson", "Specialist", "Talent Acquisition Specialist", 1, 9],
    ["Leo Anderson", "Specialist", "Systems Administrator", 2, 8],
    ["Emma Wilson", "Specialist", "Brand Designer", 3, 7],
    ["James Park", "Rank & File", "Customer Success Associate", 7, 3],
  ];
  const colors = ["teal", "blue", "amber", "violet", "rose", "slate"];
  const employees: Employee[] = rows.map(([name, profile, title, dept, manager], index) => ({
    id: demoId(index + 1),
    employee_number: `CH-${String(index + 1).padStart(4, "0")}`,
    full_name: name,
    email: `${name.toLowerCase().replaceAll(" ", ".")}@example.test`,
    phone: `+63 917 555 ${String(1000 + index)}`,
    job_title: title,
    profile_type: profile,
    department_id: departmentId(dept),
    team_id: demoId(200 + dept),
    manager_id: manager ? demoId(manager) : null,
    employment_status: index === 14 ? "Probation" : "Active",
    start_date:
      index > 18
        ? day(-20 - index)
        : `${year - (index % 4) - 1}-${String((index % 12) + 1).padStart(2, "0")}-15`,
    location: index % 5 === 0 ? "Remote" : index % 4 === 0 ? "Cebu office" : "Manila office",
    avatar_color: colors[index % colors.length],
    photo_path: null,
  }));
  const leaveTypes = [
    { id: demoId(301), name: "Annual leave", color: "teal", annual_allowance: 15 },
    { id: demoId(302), name: "Sick leave", color: "blue", annual_allowance: 10 },
    { id: demoId(303), name: "Personal leave", color: "violet", annual_allowance: 5 },
    { id: demoId(304), name: "Wellness day", color: "amber", annual_allowance: 3 },
  ];
  const leaves = [
    {
      id: demoId(701),
      employee_id: demoId(11),
      leave_type_id: demoId(301),
      start_date: day(8),
      end_date: day(10),
      days: 3,
      reason: "Family time and a short trip.",
      status: "Pending",
      approver_id: demoId(9),
      delegate_id: null,
      decision_note: null,
      created_at: stamp(-1),
    },
    {
      id: demoId(702),
      employee_id: demoId(21),
      leave_type_id: demoId(303),
      start_date: day(3),
      end_date: day(3),
      days: 1,
      reason: "Personal appointment.",
      status: "Pending",
      approver_id: demoId(9),
      delegate_id: null,
      decision_note: null,
      created_at: stamp(-1, "14:30"),
    },
    {
      id: demoId(703),
      employee_id: demoId(14),
      leave_type_id: demoId(301),
      start_date: day(5),
      end_date: day(6),
      days: 2,
      reason: "Scheduled personal time.",
      status: "Pending",
      approver_id: demoId(9),
      delegate_id: null,
      decision_note: null,
      created_at: stamp(0, "08:15"),
    },
    {
      id: demoId(704),
      employee_id: demoId(9),
      leave_type_id: demoId(301),
      start_date: day(15),
      end_date: day(16),
      days: 2,
      reason: "A long weekend with family.",
      status: "Pending",
      approver_id: demoId(2),
      delegate_id: null,
      decision_note: null,
      created_at: stamp(-2),
    },
    {
      id: demoId(705),
      employee_id: demoId(17),
      leave_type_id: demoId(304),
      start_date: day(0),
      end_date: day(0),
      days: 1,
      reason: "A day to recharge.",
      status: "Approved",
      approver_id: demoId(2),
      delegate_id: null,
      decision_note: "Enjoy your day.",
      created_at: stamp(-7),
    },
    {
      id: demoId(706),
      employee_id: demoId(9),
      leave_type_id: demoId(301),
      start_date: day(-20),
      end_date: day(-17),
      days: 4,
      reason: "Personal vacation.",
      status: "Approved",
      approver_id: demoId(2),
      delegate_id: null,
      decision_note: null,
      created_at: stamp(-30),
    },
  ];
  const leaveBalances = employees.flatMap((e) =>
    leaveTypes.map((t) => ({
      employee_id: e.id,
      leave_type_id: t.id,
      year,
      allowance: t.annual_allowance,
      used: leaves
        .filter(
          (l) => l.employee_id === e.id && l.leave_type_id === t.id && l.status === "Approved",
        )
        .reduce((n, l) => n + l.days, 0),
      pending: leaves
        .filter((l) => l.employee_id === e.id && l.leave_type_id === t.id && l.status === "Pending")
        .reduce((n, l) => n + l.days, 0),
    })),
  );
  const attendance: Attendance[] = employees
    .filter((e) => e.id !== demoId(17) && e.id !== demoId(9))
    .map((e, index) => ({
      id: demoId(801 + index),
      employee_id: e.id,
      work_date: day(0),
      clock_in: stamp(0, index % 7 === 0 ? "09:12" : "08:52"),
      clock_out: null,
      status: index % 7 === 0 ? "Late" : e.location === "Remote" ? "Remote" : "Present",
      note: null,
    }));
  for (let i = 1; i <= 7; i++)
    attendance.push({
      id: demoId(850 + i),
      employee_id: demoId(9),
      work_date: day(-i),
      clock_in: stamp(-i, "08:56"),
      clock_out: stamp(-i, "18:02"),
      status: "Present",
      note: null,
    });
  for (let dayIndex = 1; dayIndex <= 6; dayIndex++)
    employees
      .filter((e) => e.id !== demoId(9))
      .slice(0, 18 + (dayIndex % 3))
      .forEach((e, i) =>
        attendance.push({
          id: demoId(4000 + dayIndex * 100 + i),
          employee_id: e.id,
          work_date: day(-dayIndex),
          clock_in: stamp(-dayIndex, i % 9 === 0 ? "09:08" : "08:54"),
          clock_out: stamp(-dayIndex, "18:00"),
          status: i % 9 === 0 ? "Late" : e.location === "Remote" ? "Remote" : "Present",
          note: null,
        }),
      );
  const documents = [
    {
      id: demoId(901),
      title: "Employee handbook 2026",
      category: "company",
      employee_id: null,
      department_id: null,
      storage_path: "demo/employee-handbook.txt",
      requires_ack: true,
      created_at: stamp(-4),
      file_size: 3840,
    },
    {
      id: demoId(902),
      title: "Flexible work policy",
      category: "company",
      employee_id: null,
      department_id: null,
      storage_path: "demo/flexible-work.txt",
      requires_ack: true,
      created_at: stamp(-10),
      file_size: 2150,
    },
    {
      id: demoId(903),
      title: "Benefits & wellbeing guide",
      category: "company",
      employee_id: null,
      department_id: null,
      storage_path: "demo/benefits.txt",
      requires_ack: false,
      created_at: stamp(-20),
      file_size: 4300,
    },
    {
      id: demoId(904),
      title: "Employment agreement",
      category: "personnel",
      employee_id: demoId(9),
      department_id: null,
      storage_path: "demo/agreement.txt",
      requires_ack: true,
      created_at: stamp(-100),
      file_size: 3100,
    },
    {
      id: demoId(905),
      title: "IT & acceptable use policy",
      category: "company",
      employee_id: null,
      department_id: null,
      storage_path: "demo/acceptable-use.txt",
      requires_ack: false,
      created_at: stamp(-35),
      file_size: 1940,
    },
    {
      id: demoId(906),
      title: "New starter welcome pack",
      category: "company",
      employee_id: null,
      department_id: departmentId(1),
      storage_path: "demo/welcome.txt",
      requires_ack: false,
      created_at: stamp(-3),
      file_size: 5200,
    },
  ];
  const payslips = [-1, -2, -3, -4].map((offset, index) => ({
    id: demoId(1001 + index),
    employee_id: demoId(9),
    period: period(offset),
    basic_pay: 58000,
    allowances: 4500,
    deductions: 3200,
    currency: "PHP",
    status: "Published",
    published_at: stamp(-30 * (index + 1)),
  }));
  return {
    viewer: demoViewer,
    employees,
    departments,
    teams,
    attendance,
    organization: { company_name: "CentralHub", timezone: "Asia/Manila", currency: "PHP" },
    overtime: [],
    planning: [],
    recommendations: [],
    holidays: [],
    positions: employees.map((e, i) => ({
      id: demoId(8000 + i),
      title: e.job_title,
      department_id: e.department_id,
    })),
    candidates: [
      {
        id: demoId(5001),
        full_name: "Avery Blake",
        email: "avery.blake@example.test",
        position_title: "People Experience Associate",
        department_id: departmentId(1),
        stage: "Interview",
        notes: "Interested in onboarding and employee experience. Schedule the team conversation.",
        hired_employee_id: null,
        created_at: stamp(-4),
      },
      {
        id: demoId(5002),
        full_name: "Jordan Ellis",
        email: "jordan.ellis@example.test",
        position_title: "Talent Coordinator",
        department_id: departmentId(1),
        stage: "Screening",
        notes: "Review application and arrange an introductory call.",
        hired_employee_id: null,
        created_at: stamp(-2),
      },
    ],
    schedules: [0, 1, 2, 3, 4].map((d, i) => ({
      id: demoId(1101 + i),
      employee_id: demoId(9),
      work_date: day(d),
      start_time: "09:00",
      end_time: "18:00",
      location: d === 2 ? "Remote" : "Manila office",
    })),
    corrections: [],
    leaveTypes,
    leaveBalances,
    leaves,
    payslips,
    documents,
    acknowledgements: [
      { document_id: demoId(902), employee_id: demoId(9), acknowledged_at: stamp(-9) },
      { document_id: demoId(904), employee_id: demoId(9), acknowledged_at: stamp(-99) },
    ],
    announcements: [
      {
        id: demoId(1201),
        title: "Good things happen when we get together",
        body: "Our next all-hands is coming up. Join us for team updates, a look at what’s next, and a few well-deserved shout-outs. Bring your questions and your favorite coffee.",
        category: "Company news",
        pinned: true,
        department_id: null,
        author_id: demoId(9),
        created_at: stamp(-1),
      },
      {
        id: demoId(1202),
        title: "A little time for your wellbeing",
        body: "A reminder that your wellness days are here to be used. Take a breath, get outside, or do something that helps you recharge. Find the details in our Benefits & wellbeing guide.",
        category: "People & culture",
        pinned: false,
        department_id: null,
        author_id: demoId(17),
        created_at: stamp(-3),
      },
      {
        id: demoId(1203),
        title: "Say hello to our newest teammates",
        body: "Emma and James have joined Marketing and Sales. Help us give them a warm welcome and make their first weeks a little easier. We’re glad you’re here!",
        category: "Team updates",
        pinned: false,
        department_id: null,
        author_id: demoId(19),
        created_at: stamp(-5),
      },
    ],
    reviews: [
      {
        id: demoId(1301),
        employee_id: demoId(9),
        reviewer_id: demoId(2),
        cycle: "Q3 growth conversation",
        due_date: day(7),
        status: "In progress",
        feedback: null,
        employee_feedback: null,
        rating: null,
      },
      {
        id: demoId(1302),
        employee_id: demoId(17),
        reviewer_id: demoId(9),
        cycle: "Q3 growth conversation",
        due_date: day(5),
        status: "In progress",
        feedback: null,
        employee_feedback:
          "I’ve enjoyed improving our new starter experience and would like to build my analytics skills.",
        rating: null,
      },
      {
        id: demoId(1303),
        employee_id: demoId(15),
        reviewer_id: demoId(8),
        cycle: "Internship check-in",
        due_date: day(10),
        status: "In progress",
        feedback: null,
        employee_feedback: null,
        rating: null,
      },
    ],
    tasks: [
      {
        id: demoId(1401),
        employee_id: demoId(9),
        title: "Review the updated employee handbook",
        description: "Read the latest policies and record your acknowledgement in Documents.",
        category: "Onboarding",
        due_date: day(2),
        completed: false,
      },
      {
        id: demoId(1402),
        employee_id: demoId(9),
        title: "Prepare for your growth conversation",
        description: "Reflect on your wins, challenges, and goals for the next quarter.",
        category: "Development",
        due_date: day(5),
        completed: false,
      },
      {
        id: demoId(1403),
        employee_id: demoId(9),
        title: "Update your emergency contact",
        description: "Check that your contact details are current in your profile settings.",
        category: "Onboarding",
        due_date: day(1),
        completed: true,
      },
      {
        id: demoId(1404),
        employee_id: demoId(13),
        title: "Complete the daily cleaning checklist",
        description: "Check reception, meeting rooms, and shared spaces. Restock supplies.",
        category: "Cleaning",
        due_date: day(0),
        completed: false,
      },
      {
        id: demoId(1405),
        employee_id: demoId(15),
        title: "Meet your mentor and set learning goals",
        description: "Schedule a 30-minute introduction with your assigned mentor.",
        category: "Onboarding",
        due_date: day(3),
        completed: false,
      },
    ],
    training: [
      {
        id: demoId(1501),
        employee_id: demoId(9),
        title: "Inclusive leadership essentials",
        category: "Learning",
        status: "In progress",
        completed_at: null,
        expires_at: null,
      },
      {
        id: demoId(1502),
        employee_id: demoId(9),
        title: "Data privacy at work",
        category: "Learning",
        status: "Completed",
        completed_at: stamp(-20),
        expires_at: day(345),
      },
      {
        id: demoId(1503),
        employee_id: demoId(14),
        title: "Workplace safety certification",
        category: "Safety certification",
        status: "Completed",
        completed_at: stamp(-60),
        expires_at: day(305),
      },
      {
        id: demoId(1504),
        employee_id: demoId(15),
        title: "Your first 30 days",
        category: "Learning",
        status: "Assigned",
        completed_at: null,
        expires_at: null,
      },
    ],
    notifications: [
      {
        id: demoId(1601),
        employee_id: demoId(9),
        title: "3 requests are ready for review",
        body: "Your teammates are planning some time away.",
        href: "/leave",
        read_at: null,
        created_at: stamp(0),
      },
      {
        id: demoId(1602),
        employee_id: demoId(9),
        title: "Your payslip is ready",
        body: "Your latest published payslip is available.",
        href: "/payroll",
        read_at: null,
        created_at: stamp(-2),
      },
      {
        id: demoId(1603),
        employee_id: demoId(9),
        title: "A new handbook to read",
        body: "Please review and acknowledge the latest handbook.",
        href: "/documents",
        read_at: null,
        created_at: stamp(-4),
      },
    ],
    events: [
      {
        id: demoId(1701),
        title: "Company all-hands",
        event_date: day(2),
        time_label: "10:00 – 11:00 AM",
        category: "Company",
        department_id: null,
      },
      {
        id: demoId(1702),
        title: "New starter welcome",
        event_date: day(4),
        time_label: "2:00 – 3:00 PM",
        category: "Onboarding",
        department_id: null,
      },
      {
        id: demoId(1703),
        title: "Quarterly growth check-ins",
        event_date: day(7),
        time_label: "All day",
        category: "Development",
        department_id: null,
      },
    ],
    audit: [
      {
        id: demoId(1801),
        actor_id: demoViewer.id,
        action: "leave.approved",
        resource_type: "leave_request",
        resource_id: demoId(705),
        created_at: stamp(-2),
      },
      {
        id: demoId(1802),
        actor_id: demoViewer.id,
        action: "document.uploaded",
        resource_type: "document",
        resource_id: demoId(901),
        created_at: stamp(-4),
      },
    ],
    accounts: [],
    routes: departments.flatMap((d, index) =>
      ["leave", "attendance", "overtime", "planning"].map((request_type, i) => ({
        id: demoId(1901 + index * 4 + i),
        department_id: d.id,
        request_type,
        approver_id: d.id === departmentId(1) ? demoId(2) : demoId(9),
        delegate_id: null,
        delegate_until: null,
      })),
    ),
    summary: {
      total: employees.length,
      active: employees.length,
      on_leave: 1,
      departments: departments.map((d) => ({
        name: d.name,
        color: d.color,
        count: employees.filter((e) => e.department_id === d.id).length,
      })),
    },
    isDemo: true,
  };
}
