project_id = "centralhub-hris"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "10MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/confirm", "http://127.0.0.1:3000/auth/confirm"]
jwt_expiry = 900
enable_signup = false
enable_anonymous_sign_ins = false
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
minimum_password_length = 12

[auth.rate_limit]
email_sent = 6
sign_in_sign_ups = 30
token_verifications = 20

[auth.email]
enable_signup = false
enable_confirmations = true
double_confirm_changes = true
secure_password_change = true
max_frequency = "60s"
otp_expiry = 1800

[auth.mfa]
max_enrolled_factors = 3
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email.template.invite]
subject = "Your invitation to CentralHub"
content_path = "./templates/invite.html"
[auth.email.template.recovery]
subject = "Reset your CentralHub password"
content_path = "./templates/recovery.html"
